In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]
type(a)

list

In [3]:
a_np = np.array(a)
b_np = np.array(b)
a_np

array([1, 2, 3])

In [7]:
b_np

array([4, 5, 6])

In [4]:
type(a_np)

numpy.ndarray

In [5]:
a + b

[1, 2, 3, 4, 5, 6]

In [6]:
a_np + b_np

array([5, 7, 9])

In [8]:
a * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [9]:
a_np * 4

array([ 4,  8, 12])

In [11]:
a_np.shape # attribute

(3,)

In [12]:
a_np.dtype # attribute for data type

dtype('int64')

In [13]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c.shape

(2, 3)

In [15]:
c.size

6

In [17]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [20]:
np.linspace(1,100,11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [34]:
np.random.seed(42)
np.random.randint(1, 100)

52

In [35]:
np.random.randint(1, 100, 6)

array([93, 15, 72, 61, 21, 83])

In [48]:
np.random.seed(42)
mat = np.random.randint(1, 100, (3,4))
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [49]:
mat.shape

(3, 4)

In [50]:
mat.reshape(2, 6)

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24]])

In [51]:
mat.reshape(1, 12)

array([[52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24]])

In [52]:
mat.reshape(12, 1)

array([[52],
       [93],
       [15],
       [72],
       [61],
       [21],
       [83],
       [87],
       [75],
       [75],
       [88],
       [24]])

In [53]:
mat.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [54]:
mat.reshape(2, -1)

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24]])

In [55]:
mat.reshape(4, -1)

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [56]:
mat.reshape(-1, 6)

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24]])

In [57]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [58]:
mat.max()

93

In [59]:
mat.min()

15

In [60]:
mat.sum()

746

In [61]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [62]:
mat.max(axis=0)

array([75, 93, 88, 87])

In [63]:
mat.max(axis=1)

array([93, 87, 88])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [67]:
np.ones((3,4)) + 3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [68]:
np.ones((3,4)) * 10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [69]:
mat

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [70]:
mat > 50

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False]])

In [71]:
a = np.random.randint(1, 10, (2,3))
b = np.random.randint(1, 10, (2,3))

In [72]:
a

array([[3, 6, 5],
       [2, 8, 6]])

In [73]:
b

array([[2, 5, 1],
       [6, 9, 1]])

In [74]:
np.concatenate((a,b), axis=0)

array([[3, 6, 5],
       [2, 8, 6],
       [2, 5, 1],
       [6, 9, 1]])

In [75]:
np.concatenate((a,b), axis=1)

array([[3, 6, 5, 2, 5, 1],
       [2, 8, 6, 6, 9, 1]])

In [77]:
a = np.random.randint(1, 10, (4, 8))
a

array([[9, 8, 1, 8, 8, 3, 1, 8],
       [3, 3, 1, 5, 7, 9, 7, 9],
       [8, 2, 1, 7, 7, 8, 5, 3],
       [8, 6, 3, 1, 3, 5, 3, 1]])

In [78]:
a[:, :2] # slicing with numy arrays

array([[9, 8],
       [3, 3],
       [8, 2],
       [8, 6]])

In [79]:
a[:2, :4]

array([[9, 8, 1, 8],
       [3, 3, 1, 5]])

In [80]:
a[:3, :]

array([[9, 8, 1, 8, 8, 3, 1, 8],
       [3, 3, 1, 5, 7, 9, 7, 9],
       [8, 2, 1, 7, 7, 8, 5, 3]])

In [81]:
import matplotlib.pyplot as plt

In [82]:
a

array([[9, 8, 1, 8, 8, 3, 1, 8],
       [3, 3, 1, 5, 7, 9, 7, 9],
       [8, 2, 1, 7, 7, 8, 5, 3],
       [8, 6, 3, 1, 3, 5, 3, 1]])

In [83]:
a[:, 0]

array([9, 3, 8, 8])

In [84]:
plt.scatter(a[:, 0], a[:, 1])